apiVersion: v1
kind: ConfigMap
metadata:
  name: efs-provisioner-dpa-1
data:
  file.system.id: fs-6b14ff2a
  aws.region: ap-southeast-1
  provisioner.name: openshift.org/aws-efs-dpa-1
  dns.name: "10.237.82.220"
